[gcp_service_account]
type = "service_account"
project_id = "obesityapp-466710"
private_key_id = "379b0d341029122d8d61b827aaf214a513a86493"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDqb0k7fenxxngy
… (tout le contenu de la clé) …
-----END PRIVATE KEY-----
"""
client_email = "sheet-accessor@obesityapp-466710.iam.gserviceaccount.com"
client_id = "106781640056920765045"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheet-accessor%40obesityapp-466710.iam.gserviceaccount.com"
